server:
  port: 9527
spring:
  application:
    name: cloud-gateway9527
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPaymentById/**  #断言,路由要匹配的路径格式
#          filters:
#            - SetPath=/{segment}
        - id: payment-route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - After=2020-07-30T10:01:37.308+08:00[Asia/Shanghai]
#            - Cookie=username,Jeffrey

#  lb://service-provider:Consul的服务名称，以{lb://服务名}进行访问
#  Path:路由要匹配的路径格式
#  SetPath:设置路径过滤器，作用是匹配后可以根据分割符进行访问路径的设置
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**   #断言,路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
