server:
  port: 3344
spring:
  application:
    name: cloud-config-center3344
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: https://github.com/feifeikuaifeiba/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: feifeikuaifeiba
          password: ab821018.
      label: master