server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment8001
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000