server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order80

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000

feign:
  hystrix:
    enabled: true